login-page-connection
ABabayan32/TenderFlexFrontend pull request #2
Opened 2023-02-16 19:09 UTC by ABabayan32

2023-02-21 09:12 UTC, lavrovpy requested changes

2023-02-21 09:12 UTC, lavrovpy commented on package.json
> +    "vue-cookie": "^1.1.4",
It is not necessary to use vue-cookie here. We can achieve the same using only built-in tools https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie

This is just FYI, no need to change anything

2023-02-21 09:12 UTC, lavrovpy commented on src/static_functions.js
> +function abortFetching() {
it seems that you do not use abortFetching anywhere. Usually, there is no need to abort fetch in most cases unless the backend takes too much time to respond. Here are more details https://stackoverflow.com/questions/31061838/how-do-i-cancel-an-http-fetch-request

2023-02-21 09:12 UTC, lavrovpy commented on src/static_functions.js
> +         "Access-Control-Allow-Origin": "*", 'Access-Control-Allow-Methods':'GET,PUT,POST,DELETE,PATCH,OPTIONS'}
nice, but better to write every key:value pair from a new line, like

```
return {
    "Access-Control-Allow-Origin": "*",
    'Access-Control-Allow-Methods':'GET,PUT,POST,DELETE,PATCH,OPTIONS'
}
```

and use quotes consistently

2023-02-21 09:12 UTC, lavrovpy commented on src/static_functions.js
> +function getAuthenticatedHeaders () {
better to use it in this way:

```
return {
    ...getHeaders(),
    Authorization: getCookie('access_token')
}
```

2023-02-21 09:12 UTC, lavrovpy commented on src/static_functions.js
> +function getCookie(cname) {
I guess you can remove this function since you use vue-cookie library

2023-02-21 09:12 UTC, lavrovpy commented on src/static_functions.js
> +    var name = cname + "=";
do not use _var_ keyword to declare a variable

2023-02-21 09:12 UTC, lavrovpy commented on src/views/Login.vue
> +      fetch('http://localhost:8080/login', {
better to move the url to a config file

2023-02-21 09:12 UTC, lavrovpy commented on src/views/Login.vue
> +    onLogin() {
better to rename onLogin --> login

2023-02-21 09:12 UTC, lavrovpy commented on src/views/Login.vue
> +            headers: {
use your getHeaders() function here

2023-02-21 09:12 UTC, lavrovpy commented on src/views/Login.vue
> +    <button @click="onLogin">Login</button>
rename onLogin --> login

2023-02-23 10:19 UTC, ABabayan32 commented
Finalizing Login page

2023-02-23 10:19 UTC, merged