Creating tenderTable
ABabayan32/TenderFlexFrontend pull request #4
Opened 2023-03-02 20:47 UTC by ABabayan32

2023-03-03 10:35 UTC, lavrovpy requested changes
good!

2023-03-03 10:35 UTC, lavrovpy commented on index.html
> +      <link href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" rel="stylesheet">
do we really need this link?

2023-03-03 10:35 UTC, lavrovpy commented on src/styles/main.css
> +  background-size: 18.75rem;
hardcoding sizes is not a good way. better to set the parent component size and apply _height: 100%_ to a child component

2023-03-03 10:35 UTC, lavrovpy commented on src/styles/main.css
> +  width: 18.75rem;
also check out about min-width and max-width. They are much more flexible that width

2023-03-03 10:35 UTC, lavrovpy commented on src/styles/main.css
> +  border: 0.0625rem solid white;
usually color names (like white) we use only for prototyping. ii is always better to use hex code instead

2023-03-03 10:35 UTC, lavrovpy commented on src/styles/main.css
> +  width: 12.5rem;
do not hardcode the width. make the button width depended on the inner text

2023-03-03 10:35 UTC, lavrovpy commented on src/views/ContractorHome/ContractorHome.vue
> +      tendersShown: true
tendersShown should be a computed property

2023-03-03 10:35 UTC, lavrovpy commented on src/views/Header/Header.vue
> +    this.tenderCount = await fetch(API_BASE_URL + '/tenders/me/count',{
nice!

2023-03-03 10:35 UTC, lavrovpy commented on src/views/Header/Header.vue
> +    this.tenderCount = await fetch(API_BASE_URL + '/tenders/me/count',{
add try ... catch to handle errors here

2023-03-03 10:35 UTC, lavrovpy commented on src/views/Header/Header.vue
> +      <button @click="onTendersClick" class="tendersButton"><button class="tendersButton"></button>
use camel case for js code and kebab case for css

2023-03-03 10:35 UTC, lavrovpy commented on src/views/Header/Header.vue
> +      <button @click="onOffersClick" class="offersButton"><button class="offersButton"></button>
onOffersClick is a bad method name

2023-03-03 10:35 UTC, lavrovpy commented on src/views/Header/Header.vue
> +@import "@/views/Header/header.css";
css should be inside Header.vue, not a separate file

2023-03-03 10:35 UTC, lavrovpy commented on src/views/Header/header.css
> +    width: 2.5rem;
avoid using hardcoded width and height for buttons

2023-03-03 10:35 UTC, lavrovpy commented on src/views/Login/Login.vue
> +@import "@/views/Login/login.css";
same here. styles specific to the login page should be inside Login.vue. If there are styles that are used in multiple components they should be global

2023-03-03 10:35 UTC, lavrovpy commented on src/views/TenderTable/TenderTable.vue
> +  <div class="tenderTable">
use kebab case

2023-03-03 10:35 UTC, lavrovpy commented on src/views/TenderTable/TenderTable.vue
> +        <td style="width: 30%;text-align: center; color: black">{{tender['awardFileKey']}}</td>
better to create css classes and move styles. by the way I think there is a better way to set column width

2023-03-03 10:35 UTC, lavrovpy commented on src/views/TenderTable/TenderTable.vue
> +        <td style="width: 20%;text-align: center; color: #42474d">{{tender['tenderStatus'] ? tender['tenderStatus'].name : ''}}</td>
better to use **dot notation** like tender.tenderStatus.name

2023-03-03 10:35 UTC, lavrovpy commented on src/views/TenderTable/TenderTable.vue
> +    <v-pagination
nice!

2023-03-03 10:35 UTC, lavrovpy commented on src/views/TenderTable/TenderTable.vue
> +        :length="(tenderCount%count !== 0) ? tenderCount/count+1 : tenderCount/count"
move it to a computed property

2023-03-03 10:35 UTC, lavrovpy commented on src/views/TenderTable/TenderTable.vue
> +        .then(response => {
add a catch block to handle errors

2023-03-03 10:35 UTC, lavrovpy commented on src/views/TenderTable/TenderTable.vue
> +      let id = +tender['id'];
if you want to convert a string to a number use Number()

2023-03-03 10:35 UTC, lavrovpy commented on src/views/TenderTable/TenderTable.vue
> +      let d = new Date(miliseconds);
better to use smth like this https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString

2023-03-05 21:28 UTC, ABabayan32 commented
I will merge requested changes with next commit.

2023-03-05 21:28 UTC, merged